### ISSUE TITLE
iobroker mihome Instanz lässt sich nicht starten

### ISSUE THREAD

**Issue by seppal123** [ioBroker/ioBroker.mihome#11]
Hi @all

Ich schaffe es nicht den mihome adapter zum laufen zu bringen.
App und gateway funktionieren.

Jede Hilfe ist willkommen.

Mfg.
  Alessandro

-----------------------------LOG--------------------------------------
host.store	2018-03-17 23:16:11.617	info	Restart adapter system.adapter.mihome.0 because enabled
host.store	2018-03-17 23:16:11.616	error	instance system.adapter.mihome.0 terminated with code 0 (OK)
mihome.0	2018-03-17 23:16:11.603	info	terminating
mihome.0	2018-03-17 23:16:11.595	error	at Manager.ondecoded (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:332:8)
mihome.0	2018-03-17 23:16:11.595	error	at Manager.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
mihome.0	2018-03-17 23:16:11.595	error	at Manager. (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-bind/index.js:21:15)
mihome.0	2018-03-17 23:16:11.595	error	at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:236:12)
mihome.0	2018-03-17 23:16:11.595	error	at Socket.onack (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:312:9)
mihome.0	2018-03-17 23:16:11.595	error	at Socket. (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:1346:35)
mihome.0	2018-03-17 23:16:11.595	error	at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:1458:21
mihome.0	2018-03-17 23:16:11.595	error	at /opt/iobroker/node_modules/iobroker.mihome/main.js:1057:21
mihome.0	2018-03-17 23:16:11.595	error	at startMihome (/opt/iobroker/node_modules/iobroker.mihome/main.js:1106:11)
mihome.0	2018-03-17 23:16:11.595	error	at new Hub (/opt/iobroker/node_modules/iobroker.mihome/lib/mihome/Hub.js:31:20)
mihome.0	2018-03-17 23:16:11.595	error	TypeError: function from() { [native code] } is not a constructor
mihome.0	2018-03-17 23:16:11.592	error	uncaught exception: function from() { [native code] } is not a constructor
mihome.0	2018-03-17 23:16:11.565	info	starting. Version 1.0.5 in /opt/iobroker/node_modules/iobroker.mihome, node: v4.2.6
mihome.0	2018-03-17 23:16:11.545	debug	statesDB connected
mihome.0	2018-03-17 23:16:11.522	debug	objectDB connected
host.store	2018-03-17 23:16:11.169	info	instance system.adapter.mihome.0 started with pid 47600

**Comment by seppal123** [comment]
Habe nodejs auf neuere Version upgegraded, nun funktioniert es.
Closing  Issue.

Mfg.
  Alessandro
