### ISSUE TITLE
Smart Plug Keine Funktion

### ISSUE THREAD

**Issue by wowik2018** [ioBroker/ioBroker.mihome#120]
```
mihome.0	2020-08-07 20:57:07.270	info	(12746) Change connection status: true
mihome.0	2020-08-07 20:57:07.265	debug	(12746) NEW device: 7811dce1644d(gateway)
mihome.0	2020-08-07 20:57:07.215	info	(12746) Change connection status: false
mihome.0	2020-08-07 20:57:07.056	info	(12746) starting. Version 1.3.0 in /opt/iobroker/node_modules/iobroker.mihome, node: v10.20.1
host.raspberrypi	2020-08-07 20:57:04.455	info	instance system.adapter.mihome.0 started with pid 12746
host.raspberrypi	2020-08-07 20:56:34.415	info	Restart adapter system.adapter.mihome.0 because enabled
host.raspberrypi	2020-08-07 20:56:34.415	info	instance system.adapter.mihome.0 terminated with code 0 (NO_ERROR)
host.raspberrypi	2020-08-07 20:56:34.415	error	Caught by controller[0]: at runCallback (timers.js:705:18)
host.raspberrypi	2020-08-07 20:56:34.415	error	Caught by controller[0]: at Immediate.setImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4855:34)
host.raspberrypi	2020-08-07 20:56:34.414	error	Caught by controller[0]: at Adapter.emit (events.js:198:13)
host.raspberrypi	2020-08-07 20:56:34.414	error	Caught by controller[0]: at Adapter.adapter.on (/opt/iobroker/node_modules/iobroker.mihome/main.js:39:24)
host.raspberrypi	2020-08-07 20:56:34.414	error	Caught by controller[0]: at Plug.Control (/opt/iobroker/node_modules/iobroker.mihome/lib/Sensors/Plug.js:73:28)
host.raspberrypi	2020-08-07 20:56:34.414	error	Caught by controller[0]: at Hub.getKey (/opt/iobroker/node_modules/iobroker.mihome/lib/Hub.js:220:31)
host.raspberrypi	2020-08-07 20:56:34.413	error	Caught by controller[0]: at Object.createCipheriv (crypto.js:109:10)
host.raspberrypi	2020-08-07 20:56:34.413	error	Caught by controller[0]: at new Cipheriv (internal/crypto/cipher.js:217:22)
host.raspberrypi	2020-08-07 20:56:34.413	error	Caught by controller[0]: at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:115:20)
host.raspberrypi	2020-08-07 20:56:34.413	error	Caught by controller[0]: at Cipheriv.createCipherBase (internal/crypto/cipher.js:79:18)
host.raspberrypi	2020-08-07 20:56:34.412	error	Caught by controller[0]: Error: Invalid key length
mihome.0	2020-08-07 20:56:33.855	info	(12729) Terminated (NO_ERROR): Without reason
mihome.0	2020-08-07 20:56:33.851	info	(12729) terminating
mihome.0	2020-08-07 20:56:33.776	error	(12729) Error: Invalid key length at Cipheriv.createCipherBase (internal/crypto/cipher.js:79:18) at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:115:20) at new Cipheriv (internal
mihome.0	2020-08-07 20:56:33.775	error	(12729) uncaught exception: Invalid key length
mihome.0	2020-08-07 20:56:32.141	debug	(12729) RAW: {"cmd":"heartbeat","model":"gateway","sid":"7811dce1644d","short_id":"0","token":"mZrUO1s2RrtGsYV6","data":{"ip":"192.168.178.31"}}
mihome.0	2020-08-07 20:56:22.105	debug	(12729) RAW: {"cmd":"heartbeat","model":"gateway","sid":"7811dce1644d","short_id":"0","token":"1nXBQoXipbpdqgso","data":{"ip":"192.168.178.31"}}
```

**Comment by GermanBluefox** [comment]
What about the error? **Invalid key length**?
